#!/usr/bin/env ruby
# ^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'shibboleth',
         path: '.'

# cookbook 'shibboleth-test',
#          path: 'test/cookbooks/shibboleth-test'
